openapi: 3.0.1
info:
  title: Swagger Cloudtrust Validation Check (KYC)
  description: 'Internal API Validation Check for Cloudtrust.'
  version: 1.0.0
servers:
- url: http://localhost:8888
tags:
- name: UserData
  description: User data information
paths:
  /validation/realms/{realm}/users/{userID}:
    get:
      tags:
      - UserData
      summary: Get user data information
      parameters:
      - name: realm
        in: path
        description: Realm name (not id!)
        required: true
        schema:
          type: string
      - name: userID
        in: path
        description: userID to retrieve
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    put:
      tags:
      - UserData
      summary: Updates user data information
      parameters:
      - name: realm
        in: path
        description: Realm name (not id!)
        required: true
        schema:
          type: string
      - name: userID
        in: path
        description: userID of user to update
        required: true
        schema:
          type: string
      - name: txnID
        in: query
        description: transaction ID (linked in events)
        required: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        200:
          description: successful operation
  /validation/realms/{realm}/users/{userID}/accreditations:
    post:
      tags:
      - UserData
      summary: Adds an accreditation
      parameters:
      - name: realm
        in: path
        description: Realm name (not id!)
        required: true
        schema:
          type: string
      - name: userID
        in: path
        description: userID of user to update
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Accreditation'
      responses:
        200:
          description: successful operation
  /validation/realms/{realm}/users/{userID}/groups:
    get:
      tags:
      - UserData
      summary: Get groups of user
      parameters:
      - name: realm
        in: path
        description: realm name (not id!)
        required: true
        schema:
          type: string
      - name: userID
        in: path
        description: User id
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Group'
components:
  schemas:
    Accreditation:
      type: object
      properties:
        name:
          type: string
        validity:
          type: string
          description: format is DD.MM.YYYY
    User:
      type: object
      required: [gender, firstName, lastName, emailAddress, phoneNumber]
      properties:
        id:
          type: string
        gender:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        phoneNumber:
          type: string
        birthDate:
          type: string
          description: format is DD.MM.YYYY
        birthLocation:
          type: string
        nationality:
          type: string
          description: ISO 3166 Alpha-2 country code
        idDocumentType:
          type: string
          enum: [ID_CARD, PASSPORT, RESIDENCE_PERMIT]
        idDocumentNumber:
          type: string
        idDocumentExpiration:
          type: string
        idDocumentCountry:
          type: string
          description: ISO 3166 Alpha-2 country code
    Check:
      type: object
      properties:
        userId:
          type: string
        operator:
          type: string
        datetime:
          type: string
          format: date-time
        status:
          type: string
        proofData:
          type: string
          format: byte
        proofType:
          type: string
        type:
          type: string
        nature:
          type: string
        txnId:
          type: string
    Group:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
security:
  - basicAuth: []