// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package events

type OperationType = int8
const (
	OperationTypeCREATE OperationType = 0
	OperationTypeUPDATE OperationType = 1
	OperationTypeDELETE OperationType = 2
	OperationTypeACTION OperationType = 3
)

var EnumNamesOperationType = map[OperationType]string{
	OperationTypeCREATE:"CREATE",
	OperationTypeUPDATE:"UPDATE",
	OperationTypeDELETE:"DELETE",
	OperationTypeACTION:"ACTION",
}

