// automatically generated by the FlatBuffers compiler, do not modify

package schema

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UserRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsUserRequest(buf []byte, offset flatbuffers.UOffsetT) *UserRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UserRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *UserRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UserRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *UserRequest) Pack() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *UserRequest) MutatePack(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *UserRequest) Realm() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func UserRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func UserRequestAddPack(builder *flatbuffers.Builder, pack int32) {
	builder.PrependInt32Slot(0, pack, 0)
}
func UserRequestAddRealm(builder *flatbuffers.Builder, realm flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(realm), 0)
}
func UserRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
