package middleware

import (
	"context"
	"fmt"
	"math/rand"
	"strconv"
	"testing"
	"time"

	"github.com/cloudtrust/keycloak-bridge/pkg/event"
	"github.com/cloudtrust/keycloak-bridge/pkg/event/flatbuffer/fb"
	"github.com/go-kit/kit/metrics"
	flatbuffers "github.com/google/flatbuffers/go"
	opentracing "github.com/opentracing/opentracing-go"
	opentracing_log "github.com/opentracing/opentracing-go/log"
	"github.com/stretchr/testify/assert"
)

func TestEndpointCorrelationIDMW(t *testing.T) {
	var mockFlaki = &mockFlaki{}
	// We use Logging middleware to read the correlation ID generated
	// by the correlationIDMiddleware.
	var mockLogger = &mockLogger{}

	// Context with correlation ID.
	rand.Seed(time.Now().UnixNano())
	var id = strconv.FormatUint(rand.Uint64(), 10)
	var ctx = context.WithValue(context.Background(), "correlation_id", id)

	var endpoints = event.NewEndpoints(MakeEndpointCorrelationIDMW(mockFlaki))

	// Event endpoint.
	var uid = rand.Int63()
	endpoints = endpoints.MakeKeycloakEndpoint(&mockMuxComponent{fail: false}, MakeEndpointLoggingMW(mockLogger))
	mockLogger.called = false
	mockLogger.correlationID = ""
	endpoints.Event(ctx, "Event", createEventBytes(fb.EventTypeCLIENT_DELETE, uid, "realm"))
	assert.True(t, mockLogger.called)
	assert.Equal(t, id, mockLogger.correlationID)

	// Event endpoint without correlation ID.
	mockLogger.called = false
	mockLogger.correlationID = ""
	// Set the id generated by Flaki.
	var expectedID = strconv.FormatUint(rand.Uint64(), 10)
	mockFlaki.id = expectedID
	endpoints.Event(context.Background(), "Event", createEventBytes(fb.EventTypeCLIENT_DELETE, uid, "realm"))
	assert.True(t, mockLogger.called)
	assert.Equal(t, expectedID, mockLogger.correlationID)
}

func TestEndpointLoggingMW(t *testing.T) {
	var mockLogger = &mockLogger{}

	// Context with correlation ID.
	rand.Seed(time.Now().UnixNano())
	var id = strconv.FormatUint(rand.Uint64(), 10)
	var ctx = context.WithValue(context.Background(), "correlation_id", id)

	var endpoints = event.NewEndpoints(MakeEndpointLoggingMW(mockLogger))

	// Event.
	var uid = rand.Int63()
	endpoints = endpoints.MakeKeycloakEndpoint(&mockMuxComponent{fail: false})
	mockLogger.called = false
	mockLogger.correlationID = ""
	endpoints.Event(ctx, "Event", createEventBytes(fb.EventTypeCLIENT_DELETE, uid, "realm"))
	assert.True(t, mockLogger.called)
	assert.Equal(t, id, mockLogger.correlationID)

	// Event without correlation ID.
	var f = func() {
		endpoints.Event(context.Background(), "Event", createEventBytes(fb.EventTypeCLIENT_DELETE, uid, "realm"))
	}
	assert.Panics(t, f)

}

func TestEndpointInstrumentingMW(t *testing.T) {
	var mockHistogram = &mockHistogram{}

	// Context with correlation ID.
	rand.Seed(time.Now().UnixNano())
	var id = strconv.FormatUint(rand.Uint64(), 10)
	var ctx = context.WithValue(context.Background(), "correlation_id", id)

	var endpoints = event.NewEndpoints(MakeEndpointInstrumentingMW(mockHistogram))

	// Event.
	var uid = rand.Int63()
	endpoints = endpoints.MakeKeycloakEndpoint(&mockMuxComponent{fail: false})
	mockHistogram.called = false
	mockHistogram.correlationID = ""
	endpoints.Event(ctx, "Event", createEventBytes(fb.EventTypeCLIENT_DELETE, uid, "realm"))
	assert.True(t, mockHistogram.called)
	assert.Equal(t, id, mockHistogram.correlationID)

	// Event without correlation ID.
	var f = func() {
		endpoints.Event(context.Background(), "Event", createEventBytes(fb.EventTypeCLIENT_DELETE, uid, "realm"))
	}
	assert.Panics(t, f)
}

func TestEndpointTracingMW(t *testing.T) {
	var mockSpan = &mockSpan{}
	var mockTracer = &mockTracer{span: mockSpan}

	// Context with correlation ID and span.
	rand.Seed(time.Now().UnixNano())
	var id = strconv.FormatUint(rand.Uint64(), 10)
	var ctx = context.WithValue(context.Background(), "correlation_id", id)
	ctx = opentracing.ContextWithSpan(ctx, mockTracer.StartSpan("keycloak"))

	var endpoints = event.NewEndpoints(MakeEndpointTracingMW(mockTracer, "keycloak"))

	// Event.
	var uid = rand.Int63()
	endpoints = endpoints.MakeKeycloakEndpoint(&mockMuxComponent{fail: false})
	mockTracer.called = false
	endpoints.Event(ctx, "Event", createEventBytes(fb.EventTypeCLIENT_DELETE, uid, "realm"))
	assert.True(t, mockTracer.called)
	assert.Equal(t, id, mockTracer.span.correlationID)

	// Event without correlation ID.
	var f = func() {
		endpoints.Event(opentracing.ContextWithSpan(context.Background(), mockTracer.StartSpan("keycloak")), "Event", createEventBytes(fb.EventTypeCLIENT_DELETE, uid, "realm"))
	}
	assert.Panics(t, f)
}

func createEventBytes(eventType int8, uid int64, realm string) []byte {
	var builder = flatbuffers.NewBuilder(0)
	var realmStr = builder.CreateString(realm)
	fb.EventStart(builder)
	fb.EventAddUid(builder, uid)
	fb.EventAddTime(builder, time.Now().Unix())
	fb.EventAddType(builder, eventType)
	fb.EventAddRealmId(builder, realmStr)
	var eventOffset = fb.EventEnd(builder)
	builder.Finish(eventOffset)
	return builder.FinishedBytes()
}

// Mock Flaki.
type mockFlaki struct {
	id   string
	fail bool
}

func (f *mockFlaki) GetCorrelationID(_ context.Context) (string, error) {
	if f.fail {
		return "", fmt.Errorf("fail")
	}
	return f.id, nil
}

// Mock MuxComponent.
type mockMuxComponent struct {
	fail bool
}

func (c *mockMuxComponent) Event(ctx context.Context, eventType string, obj []byte) (interface{}, error) {
	if c.fail {
		return "", fmt.Errorf("fail")
	}
	return "", nil
}

// Mock Logger.
type mockLogger struct {
	called        bool
	correlationID string
}

func (l *mockLogger) Log(keyvals ...interface{}) error {
	l.called = true

	for i, kv := range keyvals {
		if kv == "correlation_id" {
			l.correlationID = keyvals[i+1].(string)
		}
	}
	return nil
}

// Mock histogram.
type mockHistogram struct {
	called        bool
	correlationID string
}

func (h *mockHistogram) With(labelValues ...string) metrics.Histogram {
	for i, kv := range labelValues {
		if kv == "correlation_id" {
			h.correlationID = labelValues[i+1]
		}
	}
	return h
}

func (h *mockHistogram) Observe(value float64) {
	h.called = true
}

// Mock Tracer.
type mockTracer struct {
	called bool
	span   *mockSpan
}

func (t *mockTracer) StartSpan(operationName string, opts ...opentracing.StartSpanOption) opentracing.Span {
	t.called = true
	return t.span
}
func (t *mockTracer) Inject(sm opentracing.SpanContext, format interface{}, carrier interface{}) error {
	return nil
}
func (t *mockTracer) Extract(format interface{}, carrier interface{}) (opentracing.SpanContext, error) {
	return nil, nil
}

// Mock Span.
type mockSpan struct {
	correlationID string
}

func (s *mockSpan) SetTag(key string, value interface{}) opentracing.Span {
	if key == "correlation_id" {
		s.correlationID = value.(string)
	}
	return s
}
func (s *mockSpan) Finish()                                                     {}
func (s *mockSpan) FinishWithOptions(opts opentracing.FinishOptions)            {}
func (s *mockSpan) Context() opentracing.SpanContext                            { return nil }
func (s *mockSpan) SetOperationName(operationName string) opentracing.Span      { return s }
func (s *mockSpan) LogFields(fields ...opentracing_log.Field)                   {}
func (s *mockSpan) LogKV(alternatingKeyValues ...interface{})                   {}
func (s *mockSpan) SetBaggageItem(restrictedKey, value string) opentracing.Span { return s }
func (s *mockSpan) BaggageItem(restrictedKey string) string                     { return "" }
func (s *mockSpan) Tracer() opentracing.Tracer                                  { return nil }
func (s *mockSpan) LogEvent(event string)                                       {}
func (s *mockSpan) LogEventWithPayload(event string, payload interface{})       {}
func (s *mockSpan) Log(data opentracing.LogData)                                {}
