// automatically generated by the FlatBuffers compiler, do not modify

package fb

const (
	OperationTypeCREATE = 0
	OperationTypeUPDATE = 1
	OperationTypeDELETE = 2
	OperationTypeACTION = 3
)

var EnumNamesOperationType = map[int]string{
	OperationTypeCREATE:"CREATE",
	OperationTypeUPDATE:"UPDATE",
	OperationTypeDELETE:"DELETE",
	OperationTypeACTION:"ACTION",
}

