services:
  bridge:
    container_name: dev-bridge
    image: mcr.microsoft.com/devcontainers/go:2.3.3-1.27@sha256:8f1c83128e4bce9d745b1dc0f28f8c027e303d3886e2434966ff135296c41770
    ports:
      - "8899:8899"
      - "8888:8888"
      - "8877:8877"
      - "8866:8866"
      - "8855:8855"
      - "8844:8844"
      - "8870:8870"
    volumes:
      - ${BRIDGE_REPOSITORY_FOLDER}:/workspace:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
