services:
  bridge:
    container_name: dev-bridge
    image: mcr.microsoft.com/devcontainers/go:2.1.3-1.26@sha256:c249440b024e82a569726ab41e60400237665d1f259fb575fd707b04b1b44e55
    ports:
      - "8899:8899"
      - "8888:8888"
      - "8877:8877"
      - "8866:8866"
      - "8855:8855"
      - "8844:8844"
      - "8870:8870"
    volumes:
      - ${BRIDGE_REPOSITORY_FOLDER}:/workspace:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
