package main

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"
	"io"
	"math/rand"
	"net"
	"net/http"
	"net/http/pprof"
	"os"
	"os/signal"
	"sort"
	"syscall"
	"time"

	common "github.com/cloudtrust/common-healthcheck"
	"github.com/cloudtrust/go-jobs"
	"github.com/cloudtrust/go-jobs/job"
	job_lock "github.com/cloudtrust/go-jobs/lock"
	job_status "github.com/cloudtrust/go-jobs/status"
	fb_flaki "github.com/cloudtrust/keycloak-bridge/api/flaki/fb"
	"github.com/cloudtrust/keycloak-bridge/api/user/fb"
	"github.com/cloudtrust/keycloak-bridge/internal/elasticsearch"
	"github.com/cloudtrust/keycloak-bridge/internal/idgenerator"
	"github.com/cloudtrust/keycloak-bridge/internal/keycloakb"
	"github.com/cloudtrust/keycloak-bridge/internal/redis"
	"github.com/cloudtrust/keycloak-bridge/pkg/event"
	"github.com/cloudtrust/keycloak-bridge/pkg/export"
	"github.com/cloudtrust/keycloak-bridge/pkg/health"
	health_job "github.com/cloudtrust/keycloak-bridge/pkg/job"
	"github.com/cloudtrust/keycloak-bridge/pkg/middleware"
	"github.com/cloudtrust/keycloak-bridge/pkg/user"
	keycloak "github.com/cloudtrust/keycloak-client"
	"github.com/coreos/go-systemd/dbus"
	sentry "github.com/getsentry/raven-go"
	"github.com/go-kit/kit/endpoint"
	"github.com/go-kit/kit/log"
	"github.com/go-kit/kit/metrics"
	gokit_influx "github.com/go-kit/kit/metrics/influx"
	"github.com/go-kit/kit/ratelimit"
	grpc_transport "github.com/go-kit/kit/transport/grpc"
	"github.com/google/flatbuffers/go"
	"github.com/gorilla/mux"
	influx "github.com/influxdata/influxdb/client/v2"
	_ "github.com/lib/pq"
	opentracing "github.com/opentracing/opentracing-go"
	"github.com/spf13/pflag"
	"github.com/spf13/viper"
	jaeger "github.com/uber/jaeger-client-go/config"
	"golang.org/x/time/rate"
	"google.golang.org/grpc"
)

var (
	// ComponentName is the name of the component.
	ComponentName = "keycloak-bridge"
	// ComponentID is an unique ID generated by Flaki at component startup.
	ComponentID = "unknown"
	// Version of the component.
	Version = "1.1"
	// Environment is filled by the compiler.
	Environment = "unknown"
	// GitCommit is filled by the compiler.
	GitCommit = "unknown"
)

const (
	influxKey   = "influx"
	jaegerKey   = "jaeger"
	redisKey    = "redis"
	sentryKey   = "sentry"
	keycloakKey = "keycloak"
)

func init() {
	rand.Seed(time.Now().UnixNano())
}

func main() {
	// Logger.
	var logger = log.NewJSONLogger(os.Stdout)
	{
		logger = log.With(logger, "ts", log.DefaultTimestampUTC, "caller", log.DefaultCaller)
	}
	defer logger.Log("msg", "goodbye")

	// Configurations.
	var c = config(log.With(logger, "unit", "config"))
	var (
		// Component
		grpcAddr = c.GetString("component-grpc-host-port")
		httpAddr = c.GetString("component-http-host-port")

		// Flaki
		flakiAddr = c.GetString("flaki-host-port")

		// Keycloak
		keycloakConfig = keycloak.Config{
			Addr:     fmt.Sprintf("http://%s", c.GetString("keycloak-host-port")),
			Username: c.GetString("keycloak-username"),
			Password: c.GetString("keycloak-password"),
			Timeout:  c.GetDuration("keycloak-timeout"),
		}

		// Elasticsearch
		esAddr  = c.GetString("es-host-port")
		esIndex = c.GetString("es-index-name")

		// Enabled units
		cockroachEnabled  = c.GetBool("cockroach")
		influxEnabled     = c.GetBool("influx")
		jaegerEnabled     = c.GetBool("jaeger")
		redisEnabled      = c.GetBool("redis")
		sentryEnabled     = c.GetBool("sentry")
		pprofRouteEnabled = c.GetBool("pprof-route-enabled")

		// Influx
		influxHTTPConfig = influx.HTTPConfig{
			Addr:     fmt.Sprintf("http://%s", c.GetString("influx-host-port")),
			Username: c.GetString("influx-username"),
			Password: c.GetString("influx-password"),
		}
		influxBatchPointsConfig = influx.BatchPointsConfig{
			Precision:        c.GetString("influx-precision"),
			Database:         c.GetString("influx-database"),
			RetentionPolicy:  c.GetString("influx-retention-policy"),
			WriteConsistency: c.GetString("influx-write-consistency"),
		}
		influxWriteInterval = c.GetDuration("influx-write-interval")

		// Jaeger
		jaegerConfig = jaeger.Configuration{
			Disabled: !jaegerEnabled,
			Sampler: &jaeger.SamplerConfig{
				Type:              c.GetString("jaeger-sampler-type"),
				Param:             c.GetFloat64("jaeger-sampler-param"),
				SamplingServerURL: fmt.Sprintf("http://%s", c.GetString("jaeger-sampler-host-port")),
			},
			Reporter: &jaeger.ReporterConfig{
				LogSpans:            c.GetBool("jaeger-reporter-logspan"),
				BufferFlushInterval: c.GetDuration("jaeger-write-interval"),
			},
		}
		jaegerCollectorHealthcheckURL = c.GetString("jaeger-collector-healthcheck-host-port")

		// Sentry
		sentryDSN = c.GetString("sentry-dsn")

		// Redis
		redisURL           = c.GetString("redis-host-port")
		redisPassword      = c.GetString("redis-password")
		redisDatabase      = c.GetInt("redis-database")
		redisWriteInterval = c.GetDuration("redis-write-interval")

		// Cockroach
		cockroachHostPort      = c.GetString("cockroach-host-port")
		cockroachUsername      = c.GetString("cockroach-username")
		cockroachPassword      = c.GetString("cockroach-password")
		cockroachDB            = c.GetString("cockroach-database")
		cockroachCleanInterval = c.GetDuration("cockroach-clean-interval")

		// Jobs
		healthChecksValidity = map[string]time.Duration{
			influxKey:   c.GetDuration("job-influx-health-validity"),
			jaegerKey:   c.GetDuration("job-jaeger-health-validity"),
			redisKey:    c.GetDuration("job-redis-health-validity"),
			sentryKey:   c.GetDuration("job-sentry-health-validity"),
			keycloakKey: c.GetDuration("job-keycloak-health-validity"),
		}

		// Rate limiting
		rateLimit = map[string]int{
			"event":              c.GetInt("rate-event"),
			"user":               c.GetInt("rate-user"),
			"influxHealthExec":   c.GetInt("rate-influx-health-exec"),
			"influxHealthRead":   c.GetInt("rate-influx-health-read"),
			"jaegerHealthExec":   c.GetInt("rate-jaeger-health-exec"),
			"jaegerHealthRead":   c.GetInt("rate-jaeger-health-read"),
			"redisHealthExec":    c.GetInt("rate-redis-health-exec"),
			"redisHealthRead":    c.GetInt("rate-redis-health-read"),
			"sentryHealthExec":   c.GetInt("rate-sentry-health-exec"),
			"sentryHealthRead":   c.GetInt("rate-sentry-health-read"),
			"keycloakHealthExec": c.GetInt("rate-keycloak-health-exec"),
			"keycloakHealthRead": c.GetInt("rate-keycloak-health-read"),
			"allHealth":          c.GetInt("rate-all-health"),
		}
	)

	// Redis.
	type Redis interface {
		Close() error
		Do(commandName string, args ...interface{}) (reply interface{}, err error)
		Send(commandName string, args ...interface{}) error
		Flush() error
	}

	var redisConn Redis = &keycloakb.NoopRedis{}
	if redisEnabled {
		var err error
		redisConn, err = redis.NewResilientConn(redisURL, redisPassword, redisDatabase)
		if err != nil {
			logger.Log("msg", "could not create redis client", "error", err)
			return
		}
		defer redisConn.Close()

		// Create logger that duplicates logs to stdout and redis.
		logger = log.NewJSONLogger(io.MultiWriter(os.Stdout, keycloakb.NewLogstashRedisWriter(redisConn, ComponentName)))
		logger = log.With(logger, "ts", log.DefaultTimestampUTC, "caller", log.DefaultCaller)
	}

	// Flaki.
	var flakiClient fb_flaki.FlakiClient
	{
		// Set up a connection to the flaki-service.
		var conn *grpc.ClientConn
		{
			var err error
			conn, err = grpc.Dial(flakiAddr, grpc.WithInsecure(), grpc.WithCodec(flatbuffers.FlatbuffersCodec{}))
			if err != nil {
				logger.Log("msg", "could not connect to flaki-service", "error", err)
				return
			}
			defer conn.Close()
		}

		flakiClient = fb_flaki.NewFlakiClient(conn)
	}

	// Get unique ID for this component
	{
		var b = flatbuffers.NewBuilder(0)
		fb_flaki.FlakiRequestStart(b)
		b.Finish(fb_flaki.FlakiRequestEnd(b))

		var res, err = flakiClient.NextValidID(context.Background(), b)
		if err != nil {
			logger.Log("msg", "could not connect to flaki-service", "error", err)
			return
		}
		ComponentID = string(res.Id())
	}

	// Add component name, component ID and version to the logger tags.
	logger = log.With(logger, "component_name", ComponentName, "component_id", ComponentID, "component_version", Version)

	// Log component version infos.
	logger.Log("environment", Environment, "git_commit", GitCommit)

	// Critical errors channel.
	var errc = make(chan error)
	go func() {
		var c = make(chan os.Signal, 1)
		signal.Notify(c, syscall.SIGINT, syscall.SIGTERM)
		errc <- fmt.Errorf("%s", <-c)
	}()

	// Keycloak client.
	var keycloakClient *keycloak.Client
	{
		var err error
		keycloakClient, err = keycloak.New(keycloakConfig)
		if err != nil {
			logger.Log("msg", "could not create Keycloak client", "error", err)
			return
		}
	}

	// Sentry.
	type Sentry interface {
		CaptureError(err error, tags map[string]string, interfaces ...sentry.Interface) string
		URL() string
		Close()
	}

	var sentryClient Sentry = &keycloakb.NoopSentry{}
	if sentryEnabled {
		var logger = log.With(logger, "unit", "sentry")
		var err error
		sentryClient, err = sentry.New(sentryDSN)
		if err != nil {
			logger.Log("msg", "could not create Sentry client", "error", err)
			return
		}
		defer sentryClient.Close()
	}

	// Influx client.
	type Metrics interface {
		NewCounter(name string) metrics.Counter
		NewGauge(name string) metrics.Gauge
		NewHistogram(name string) metrics.Histogram
		WriteLoop(c <-chan time.Time)
		Write(bp influx.BatchPoints) error
		Ping(timeout time.Duration) (time.Duration, string, error)
	}

	var influxMetrics Metrics = &keycloakb.NoopMetrics{}
	if influxEnabled {
		var logger = log.With(logger, "unit", "influx")

		var influxClient, err = influx.NewHTTPClient(influxHTTPConfig)
		if err != nil {
			logger.Log("msg", "could not create Influx client", "error", err)
			return
		}
		defer influxClient.Close()

		var gokitInflux = gokit_influx.New(
			map[string]string{},
			influxBatchPointsConfig,
			log.With(logger, "unit", "go-kit influx"),
		)

		influxMetrics = keycloakb.NewMetrics(influxClient, gokitInflux)
	}

	// Jaeger client.
	var tracer opentracing.Tracer
	{
		var logger = log.With(logger, "unit", "jaeger")
		var closer io.Closer
		var err error

		tracer, closer, err = jaegerConfig.New(ComponentName)
		if err != nil {
			logger.Log("msg", "could not create Jaeger tracer", "error", err)
			return
		}
		defer closer.Close()
	}

	// Systemd D-Bus connection.
	var systemDConn *dbus.Conn
	{
		var err error
		systemDConn, err = dbus.New()
		if err != nil {
			logger.Log("msg", "could not create systemd D-Bus connection", "error", err)
			return
		}
	}

	// Cockroach DB.
	type Cockroach interface {
		Exec(query string, args ...interface{}) (sql.Result, error)
		Query(query string, args ...interface{}) (*sql.Rows, error)
		QueryRow(query string, args ...interface{}) *sql.Row
	}

	var cockroachConn Cockroach
	if cockroachEnabled {
		var err error
		cockroachConn, err = sql.Open("postgres", fmt.Sprintf("postgresql://%s:%s@%s/%s?sslmode=disable", cockroachUsername, cockroachPassword, cockroachHostPort, cockroachDB))
		if err != nil {
			logger.Log("msg", "could not create cockroach DB connection for config DB", "error", err)
			return
		}
	}

	// Elasticsearch client.
	var esClient = elasticsearch.NewClient(esAddr, http.DefaultClient)

	// User service.
	var userLogger = log.With(logger, "svc", "user")

	var userModule user.Module
	{
		userModule = user.NewModule(keycloakClient)
		userModule = user.MakeModuleInstrumentingMW(influxMetrics.NewHistogram("user_module"))(userModule)
		userModule = user.MakeModuleLoggingMW(log.With(userLogger, "mw", "module"))(userModule)
		userModule = user.MakeModuleTracingMW(tracer)(userModule)
	}

	var userComponent user.Component
	{
		userComponent = user.NewComponent(userModule)
		userComponent = user.MakeComponentInstrumentingMW(influxMetrics.NewHistogram("user_component"))(userComponent)
		userComponent = user.MakeComponentLoggingMW(log.With(userLogger, "mw", "component"))(userComponent)
		userComponent = user.MakeComponentTracingMW(tracer)(userComponent)
		userComponent = user.MakeComponentTrackingMW(sentryClient, log.With(userLogger, "mw", "component"))(userComponent)
	}

	var userEndpoint endpoint.Endpoint
	{
		userEndpoint = user.MakeGetUsersEndpoint(userComponent)
		userEndpoint = middleware.MakeEndpointInstrumentingMW(influxMetrics.NewHistogram("user_endpoint"))(userEndpoint)
		userEndpoint = middleware.MakeEndpointLoggingMW(log.With(userLogger, "mw", "endpoint", "unit", "getusers"))(userEndpoint)
		userEndpoint = middleware.MakeEndpointTracingMW(tracer, "user_endpoint")(userEndpoint)
		userEndpoint = middleware.MakeEndpointCorrelationIDMW(flakiClient, tracer)(userEndpoint)
	}
	// Rate limiting
	userEndpoint = ratelimit.NewErroringLimiter(rate.NewLimiter(rate.Every(time.Second), rateLimit["user"]))(userEndpoint)

	var userEndpoints = user.Endpoints{
		Endpoint: userEndpoint,
	}

	// Event service.
	var eventLogger = log.With(logger, "svc", "event")

	var consoleModule event.ConsoleModule
	{
		consoleModule = event.NewConsoleModule(log.With(eventLogger, "module", "console"), esClient, esIndex, ComponentName, ComponentID)
		consoleModule = event.MakeConsoleModuleInstrumentingMW(influxMetrics.NewHistogram("console_module"))(consoleModule)
		consoleModule = event.MakeConsoleModuleLoggingMW(log.With(eventLogger, "mw", "module", "unit", "console"))(consoleModule)
		consoleModule = event.MakeConsoleModuleTracingMW(tracer)(consoleModule)
	}

	var statisticModule event.StatisticModule
	{
		statisticModule = event.NewStatisticModule(influxMetrics, influxBatchPointsConfig)
		statisticModule = event.MakeStatisticModuleInstrumentingMW(influxMetrics.NewHistogram("statistic_module"))(statisticModule)
		statisticModule = event.MakeStatisticModuleLoggingMW(log.With(eventLogger, "mw", "module", "unit", "statistic"))(statisticModule)
		statisticModule = event.MakeStatisticModuleTracingMW(tracer)(statisticModule)
	}

	var eventAdminComponent event.AdminComponent
	{
		var fns = []event.FuncEvent{consoleModule.Print, statisticModule.Stats}
		eventAdminComponent = event.NewAdminComponent(fns, fns, fns, fns)
		eventAdminComponent = event.MakeAdminComponentInstrumentingMW(influxMetrics.NewHistogram("admin_component"))(eventAdminComponent)
		eventAdminComponent = event.MakeAdminComponentLoggingMW(log.With(eventLogger, "mw", "component", "unit", "admin_event"))(eventAdminComponent)
		eventAdminComponent = event.MakeAdminComponentTracingMW(tracer)(eventAdminComponent)
	}

	var eventComponent event.Component
	{
		var fns = []event.FuncEvent{consoleModule.Print, statisticModule.Stats}
		eventComponent = event.NewComponent(fns, fns)
		eventComponent = event.MakeComponentInstrumentingMW(influxMetrics.NewHistogram("component"))(eventComponent)
		eventComponent = event.MakeComponentLoggingMW(log.With(eventLogger, "mw", "component", "unit", "event"))(eventComponent)
		eventComponent = event.MakeComponentTracingMW(tracer)(eventComponent)
	}

	var muxComponent event.MuxComponent
	{
		muxComponent = event.NewMuxComponent(eventComponent, eventAdminComponent)
		muxComponent = event.MakeMuxComponentInstrumentingMW(influxMetrics.NewHistogram("mux_component"))(muxComponent)
		muxComponent = event.MakeMuxComponentLoggingMW(log.With(eventLogger, "mw", "component", "unit", "mux"))(muxComponent)
		muxComponent = event.MakeMuxComponentTracingMW(tracer)(muxComponent)
		muxComponent = event.MakeMuxComponentTrackingMW(sentryClient, log.With(eventLogger, "mw", "component"))(muxComponent)
	}

	var eventEndpoint endpoint.Endpoint
	{
		eventEndpoint = event.MakeEventEndpoint(muxComponent)
		eventEndpoint = middleware.MakeEndpointInstrumentingMW(influxMetrics.NewHistogram("event_endpoint"))(eventEndpoint)
		eventEndpoint = middleware.MakeEndpointLoggingMW(log.With(eventLogger, "mw", "endpoint"))(eventEndpoint)
		eventEndpoint = middleware.MakeEndpointTracingMW(tracer, "event_endpoint")(eventEndpoint)
		eventEndpoint = middleware.MakeEndpointCorrelationIDMW(flakiClient, tracer)(eventEndpoint)
	}

	// Rate limiting
	eventEndpoint = ratelimit.NewErroringLimiter(rate.NewLimiter(rate.Every(time.Second), rateLimit["event"]))(eventEndpoint)

	var eventEndpoints = event.Endpoints{
		Endpoint: eventEndpoint,
	}

	// Export configuration
	var exportModule = export.NewModule(keycloakClient)
	var cfgStorageModue = export.NewConfigStorageModule(cockroachConn)

	var exportComponent = export.NewComponent(ComponentName, Version, exportModule, cfgStorageModue)
	var exportEndpoint = export.MakeExportEndpoint(exportComponent)
	var exportSaveAndExportEndpoint = export.MakeStoreAndExportEndpoint(exportComponent)

	// Health service.
	var healthLogger = log.With(logger, "svc", "health")

	var cockroachModule *health.StorageModule
	{
		cockroachModule = health.NewStorageModule(ComponentName, ComponentID, cockroachConn)
	}

	var influxHM health.InfluxHealthChecker
	{
		influxHM = common.NewInfluxModule(influxMetrics, influxEnabled)
		influxHM = common.MakeInfluxModuleLoggingMW(log.With(healthLogger, "mw", "module"))(influxHM)
	}
	var jaegerHM health.JaegerHealthChecker
	{
		jaegerHM = common.NewJaegerModule(systemDConn, http.DefaultClient, jaegerCollectorHealthcheckURL, jaegerEnabled)
		jaegerHM = common.MakeJaegerModuleLoggingMW(log.With(healthLogger, "mw", "module"))(jaegerHM)
	}
	var redisHM health.RedisHealthChecker
	{
		redisHM = common.NewRedisModule(redisConn, redisEnabled)
		redisHM = common.MakeRedisModuleLoggingMW(log.With(healthLogger, "mw", "module"))(redisHM)
	}
	var sentryHM health.SentryHealthChecker
	{
		sentryHM = common.NewSentryModule(sentryClient, http.DefaultClient, sentryEnabled)
		sentryHM = common.MakeSentryModuleLoggingMW(log.With(healthLogger, "mw", "module"))(sentryHM)
	}
	var keycloakHM health.KeycloakHealthChecker
	{
		var err error
		keycloakHM, err = health.NewKeycloakModule(keycloakClient, Version)
		if err != nil {
			logger.Log("msg", "could not create keycloak health check module", "error", err)
			return
		}
	}

	var healthComponent health.HealthChecker
	{
		healthComponent = health.NewComponent(influxHM, jaegerHM, redisHM, sentryHM, keycloakHM, cockroachModule, healthChecksValidity)
		healthComponent = health.MakeComponentLoggingMW(log.With(healthLogger, "mw", "component"))(healthComponent)
	}

	var influxExecHealthEndpoint endpoint.Endpoint
	{
		influxExecHealthEndpoint = health.MakeExecInfluxHealthCheckEndpoint(healthComponent)
		influxExecHealthEndpoint = middleware.MakeEndpointLoggingMW(log.With(healthLogger, "mw", "endpoint", "unit", "ExecInfluxHealthCheck"))(influxExecHealthEndpoint)
		influxExecHealthEndpoint = middleware.MakeEndpointCorrelationIDMW(flakiClient, tracer)(influxExecHealthEndpoint)
	}
	var influxReadHealthEndpoint endpoint.Endpoint
	{
		influxReadHealthEndpoint = health.MakeReadInfluxHealthCheckEndpoint(healthComponent)
		influxReadHealthEndpoint = middleware.MakeEndpointLoggingMW(log.With(healthLogger, "mw", "endpoint", "unit", "ReadInfluxHealthCheck"))(influxReadHealthEndpoint)
		influxReadHealthEndpoint = middleware.MakeEndpointCorrelationIDMW(flakiClient, tracer)(influxReadHealthEndpoint)
	}
	var jaegerExecHealthEndpoint endpoint.Endpoint
	{
		jaegerExecHealthEndpoint = health.MakeExecJaegerHealthCheckEndpoint(healthComponent)
		jaegerExecHealthEndpoint = middleware.MakeEndpointLoggingMW(log.With(healthLogger, "mw", "endpoint", "unit", "ExecJaegerHealthCheck"))(jaegerExecHealthEndpoint)
		jaegerExecHealthEndpoint = middleware.MakeEndpointCorrelationIDMW(flakiClient, tracer)(jaegerExecHealthEndpoint)
	}
	var jaegerReadHealthEndpoint endpoint.Endpoint
	{
		jaegerReadHealthEndpoint = health.MakeReadJaegerHealthCheckEndpoint(healthComponent)
		jaegerReadHealthEndpoint = middleware.MakeEndpointLoggingMW(log.With(healthLogger, "mw", "endpoint", "unit", "ReadJaegerHealthCheck"))(jaegerReadHealthEndpoint)
		jaegerReadHealthEndpoint = middleware.MakeEndpointCorrelationIDMW(flakiClient, tracer)(jaegerReadHealthEndpoint)
	}
	var redisExecHealthEndpoint endpoint.Endpoint
	{
		redisExecHealthEndpoint = health.MakeExecRedisHealthCheckEndpoint(healthComponent)
		redisExecHealthEndpoint = middleware.MakeEndpointLoggingMW(log.With(healthLogger, "mw", "endpoint", "unit", "ExecRedisHealthCheck"))(redisExecHealthEndpoint)
		redisExecHealthEndpoint = middleware.MakeEndpointCorrelationIDMW(flakiClient, tracer)(redisExecHealthEndpoint)
	}
	var redisReadHealthEndpoint endpoint.Endpoint
	{
		redisReadHealthEndpoint = health.MakeReadRedisHealthCheckEndpoint(healthComponent)
		redisReadHealthEndpoint = middleware.MakeEndpointLoggingMW(log.With(healthLogger, "mw", "endpoint", "unit", "ReadRedisHealthCheck"))(redisReadHealthEndpoint)
		redisReadHealthEndpoint = middleware.MakeEndpointCorrelationIDMW(flakiClient, tracer)(redisReadHealthEndpoint)
	}
	var sentryExecHealthEndpoint endpoint.Endpoint
	{
		sentryExecHealthEndpoint = health.MakeExecSentryHealthCheckEndpoint(healthComponent)
		sentryExecHealthEndpoint = middleware.MakeEndpointLoggingMW(log.With(healthLogger, "mw", "endpoint", "unit", "ExecSentryHealthCheck"))(sentryExecHealthEndpoint)
		sentryExecHealthEndpoint = middleware.MakeEndpointCorrelationIDMW(flakiClient, tracer)(sentryExecHealthEndpoint)
	}
	var sentryReadHealthEndpoint endpoint.Endpoint
	{
		sentryReadHealthEndpoint = health.MakeReadSentryHealthCheckEndpoint(healthComponent)
		sentryReadHealthEndpoint = middleware.MakeEndpointLoggingMW(log.With(healthLogger, "mw", "endpoint", "unit", "ReadSentryHealthCheck"))(sentryReadHealthEndpoint)
		sentryReadHealthEndpoint = middleware.MakeEndpointCorrelationIDMW(flakiClient, tracer)(sentryReadHealthEndpoint)
	}
	var keycloakExecHealthEndpoint endpoint.Endpoint
	{
		keycloakExecHealthEndpoint = health.MakeExecKeycloakHealthCheckEndpoint(healthComponent)
		keycloakExecHealthEndpoint = middleware.MakeEndpointLoggingMW(log.With(healthLogger, "mw", "endpoint", "unit", "ExecKeycloakHealthCheck"))(keycloakExecHealthEndpoint)
		keycloakExecHealthEndpoint = middleware.MakeEndpointCorrelationIDMW(flakiClient, tracer)(keycloakExecHealthEndpoint)
	}
	var keycloakReadHealthEndpoint endpoint.Endpoint
	{
		keycloakReadHealthEndpoint = health.MakeReadKeycloakHealthCheckEndpoint(healthComponent)
		keycloakReadHealthEndpoint = middleware.MakeEndpointLoggingMW(log.With(healthLogger, "mw", "endpoint", "unit", "ReadKeycloakHealthCheck"))(keycloakReadHealthEndpoint)
		keycloakReadHealthEndpoint = middleware.MakeEndpointCorrelationIDMW(flakiClient, tracer)(keycloakReadHealthEndpoint)
	}
	var allHealthEndpoint endpoint.Endpoint
	{
		allHealthEndpoint = health.MakeAllHealthChecksEndpoint(healthComponent)
		allHealthEndpoint = middleware.MakeEndpointLoggingMW(log.With(healthLogger, "mw", "endpoint", "unit", "AllHealthCheck"))(allHealthEndpoint)
		allHealthEndpoint = middleware.MakeEndpointCorrelationIDMW(flakiClient, tracer)(allHealthEndpoint)
	}

	// Rate limiting
	influxExecHealthEndpoint = ratelimit.NewErroringLimiter(rate.NewLimiter(rate.Every(time.Second), rateLimit["influxHealthExec"]))(influxExecHealthEndpoint)
	influxReadHealthEndpoint = ratelimit.NewErroringLimiter(rate.NewLimiter(rate.Every(time.Second), rateLimit["influxHealthRead"]))(influxReadHealthEndpoint)
	jaegerExecHealthEndpoint = ratelimit.NewErroringLimiter(rate.NewLimiter(rate.Every(time.Second), rateLimit["jaegerHealthExec"]))(jaegerExecHealthEndpoint)
	jaegerReadHealthEndpoint = ratelimit.NewErroringLimiter(rate.NewLimiter(rate.Every(time.Second), rateLimit["jaegerHealthRead"]))(jaegerReadHealthEndpoint)
	redisExecHealthEndpoint = ratelimit.NewErroringLimiter(rate.NewLimiter(rate.Every(time.Second), rateLimit["redisHealthExec"]))(redisExecHealthEndpoint)
	redisReadHealthEndpoint = ratelimit.NewErroringLimiter(rate.NewLimiter(rate.Every(time.Second), rateLimit["redisHealthRead"]))(redisReadHealthEndpoint)
	sentryExecHealthEndpoint = ratelimit.NewErroringLimiter(rate.NewLimiter(rate.Every(time.Second), rateLimit["sentryHealthExec"]))(sentryExecHealthEndpoint)
	sentryReadHealthEndpoint = ratelimit.NewErroringLimiter(rate.NewLimiter(rate.Every(time.Second), rateLimit["sentryHealthRead"]))(sentryReadHealthEndpoint)
	keycloakExecHealthEndpoint = ratelimit.NewErroringLimiter(rate.NewLimiter(rate.Every(time.Second), rateLimit["keycloakHealthExec"]))(keycloakExecHealthEndpoint)
	keycloakReadHealthEndpoint = ratelimit.NewErroringLimiter(rate.NewLimiter(rate.Every(time.Second), rateLimit["keycloakHealthRead"]))(keycloakReadHealthEndpoint)
	allHealthEndpoint = ratelimit.NewErroringLimiter(rate.NewLimiter(rate.Every(time.Second), rateLimit["allHealth"]))(allHealthEndpoint)

	var healthEndpoints = health.Endpoints{
		InfluxExecHealthCheck:   influxExecHealthEndpoint,
		InfluxReadHealthCheck:   influxReadHealthEndpoint,
		JaegerExecHealthCheck:   jaegerExecHealthEndpoint,
		JaegerReadHealthCheck:   jaegerReadHealthEndpoint,
		RedisExecHealthCheck:    redisExecHealthEndpoint,
		RedisReadHealthCheck:    redisReadHealthEndpoint,
		SentryExecHealthCheck:   sentryExecHealthEndpoint,
		SentryReadHealthCheck:   sentryReadHealthEndpoint,
		KeycloakExecHealthCheck: keycloakExecHealthEndpoint,
		KeycloakReadHealthCheck: keycloakReadHealthEndpoint,
		AllHealthChecks:         allHealthEndpoint,
	}

	// Jobs
	{
		var ctrl = controller.NewController(ComponentName, ComponentID, idgenerator.New(flakiClient, tracer), &job_lock.NoopLocker{}, controller.EnableStatusStorage(job_status.New(cockroachConn)))

		var influxJob *job.Job
		{
			var err error
			influxJob, err = health_job.MakeInfluxJob(influxHM, healthChecksValidity[influxKey], cockroachModule)
			if err != nil {
				logger.Log("msg", "could not create influx health job", "error", err)
				return
			}
			ctrl.Register(influxJob)
			ctrl.Schedule("@minutely", influxJob.Name())
		}

		var jaegerJob *job.Job
		{
			var err error
			jaegerJob, err = health_job.MakeJaegerJob(jaegerHM, healthChecksValidity[jaegerKey], cockroachModule)
			if err != nil {
				logger.Log("msg", "could not create jaeger health job", "error", err)
				return
			}
			ctrl.Register(jaegerJob)
			ctrl.Schedule("@minutely", jaegerJob.Name())
		}

		var redisJob *job.Job
		{
			var err error
			redisJob, err = health_job.MakeRedisJob(redisHM, healthChecksValidity[redisKey], cockroachModule)
			if err != nil {
				logger.Log("msg", "could not create redis health job", "error", err)
				return
			}
			ctrl.Register(redisJob)
			ctrl.Schedule("@minutely", redisJob.Name())
		}

		var sentryJob *job.Job
		{
			var err error
			sentryJob, err = health_job.MakeSentryJob(sentryHM, healthChecksValidity[sentryKey], cockroachModule)
			if err != nil {
				logger.Log("msg", "could not create sentry health job", "error", err)
				return
			}
			ctrl.Register(sentryJob)
			ctrl.Schedule("@minutely", sentryJob.Name())
		}

		var keycloakJob *job.Job
		{
			var err error
			keycloakJob, err = health_job.MakeKeycloakJob(keycloakHM, healthChecksValidity[keycloakKey], cockroachModule)
			if err != nil {
				logger.Log("msg", "could not create keycloak health job", "error", err)
				return
			}
			ctrl.Register(keycloakJob)
			ctrl.Schedule("@minutely", keycloakJob.Name())
		}

		var cleanJob *job.Job
		{
			var err error
			cleanJob, err = health_job.MakeCleanCockroachJob(cockroachModule, log.With(logger, "job", "clean health checks"))
			if err != nil {
				logger.Log("msg", "could not create clean job", "error", err)
				return
			}
			ctrl.Register(cleanJob)
			ctrl.Schedule(fmt.Sprintf("@every %s", cockroachCleanInterval), cleanJob.Name())

		}
		ctrl.Start()
	}

	// GRPC server.
	go func() {
		var logger = log.With(logger, "transport", "grpc")
		logger.Log("addr", grpcAddr)

		var lis net.Listener
		{
			var err error
			lis, err = net.Listen("tcp", grpcAddr)
			if err != nil {
				logger.Log("msg", "could not initialise listener", "error", err)
				errc <- err
				return
			}
		}

		// User Handler.
		var getUsersHandler grpc_transport.Handler
		{
			getUsersHandler = user.MakeGRPCGetUsersHandler(userEndpoints.Endpoint)
			getUsersHandler = middleware.MakeGRPCTracingMW(tracer, ComponentName, "grpc_server_getusers")(getUsersHandler)
		}

		var grpcServer = user.NewGRPCServer(getUsersHandler)
		var userServer = grpc.NewServer(grpc.CustomCodec(flatbuffers.FlatbuffersCodec{}))
		fb.RegisterUserServiceServer(userServer, grpcServer)

		errc <- userServer.Serve(lis)
	}()

	// HTTP Server.
	go func() {
		var logger = log.With(logger, "transport", "http")
		logger.Log("addr", httpAddr)

		var route = mux.NewRouter()

		// Version.
		route.Handle("/", http.HandlerFunc(makeVersion(ComponentName, ComponentID, Version, Environment, GitCommit)))

		// Event.
		var eventSubroute = route.PathPrefix("/event").Subrouter()

		var eventHandler http.Handler
		{
			eventHandler = event.MakeHTTPEventHandler(eventEndpoints.Endpoint)
			eventHandler = middleware.MakeHTTPTracingMW(tracer, ComponentName, "http_server_event")(eventHandler)
		}
		eventSubroute.Handle("/receiver", eventHandler)

		// Users.
		var getUsersHandler http.Handler
		{
			getUsersHandler = user.MakeHTTPGetUsersHandler(userEndpoints.Endpoint)
			getUsersHandler = middleware.MakeHTTPTracingMW(tracer, ComponentName, "http_server_getusers")(getUsersHandler)
		}
		route.Handle("/getusers", getUsersHandler)

		// Export.
		route.Handle("/export", export.MakeHTTPExportHandler(exportEndpoint)).Methods("GET")
		route.Handle("/export", export.MakeHTTPExportHandler(exportSaveAndExportEndpoint)).Methods("POST")

		// Health checks.
		var healthSubroute = route.PathPrefix("/health").Subrouter()

		var allHealthChecksHandler = health.MakeHealthCheckHandler(healthEndpoints.AllHealthChecks)
		healthSubroute.Handle("", allHealthChecksHandler)

		healthSubroute.Handle("/influx", health.MakeHealthCheckHandler(healthEndpoints.InfluxReadHealthCheck)).Methods("GET")
		healthSubroute.Handle("/influx", health.MakeHealthCheckHandler(healthEndpoints.InfluxExecHealthCheck)).Methods("POST")

		healthSubroute.Handle("/jaeger", health.MakeHealthCheckHandler(healthEndpoints.JaegerReadHealthCheck)).Methods("GET")
		healthSubroute.Handle("/jaeger", health.MakeHealthCheckHandler(healthEndpoints.JaegerExecHealthCheck)).Methods("POST")

		healthSubroute.Handle("/redis", health.MakeHealthCheckHandler(healthEndpoints.RedisReadHealthCheck)).Methods("GET")
		healthSubroute.Handle("/redis", health.MakeHealthCheckHandler(healthEndpoints.RedisExecHealthCheck)).Methods("POST")

		healthSubroute.Handle("/sentry", health.MakeHealthCheckHandler(healthEndpoints.SentryReadHealthCheck)).Methods("GET")
		healthSubroute.Handle("/sentry", health.MakeHealthCheckHandler(healthEndpoints.SentryExecHealthCheck)).Methods("POST")

		healthSubroute.Handle("/keycloak", health.MakeHealthCheckHandler(healthEndpoints.KeycloakReadHealthCheck)).Methods("GET")
		healthSubroute.Handle("/keycloak", health.MakeHealthCheckHandler(healthEndpoints.KeycloakExecHealthCheck)).Methods("POST")

		// Debug.
		if pprofRouteEnabled {
			var debugSubroute = route.PathPrefix("/debug").Subrouter()
			debugSubroute.HandleFunc("/pprof/", http.HandlerFunc(pprof.Index))
			debugSubroute.HandleFunc("/pprof/cmdline", http.HandlerFunc(pprof.Cmdline))
			debugSubroute.HandleFunc("/pprof/profile", http.HandlerFunc(pprof.Profile))
			debugSubroute.HandleFunc("/pprof/symbol", http.HandlerFunc(pprof.Symbol))
			debugSubroute.HandleFunc("/pprof/trace", http.HandlerFunc(pprof.Trace))
		}

		errc <- http.ListenAndServe(httpAddr, route)
	}()

	// Influx writing.
	go func() {
		var tic = time.NewTicker(influxWriteInterval)
		defer tic.Stop()
		influxMetrics.WriteLoop(tic.C)
	}()

	// Redis writing.
	if redisEnabled {
		go func() {
			var tic = time.NewTicker(redisWriteInterval)
			defer tic.Stop()
			for range tic.C {
				redisConn.Flush()
			}
		}()
	}

	logger.Log("error", <-errc)
}

// makeVersion makes a HTTP handler that returns information about the version of the bridge.
func makeVersion(componentName, ComponentID, version, environment, gitCommit string) func(http.ResponseWriter, *http.Request) {
	return func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json; charset=utf-8")

		var info = struct {
			Name    string `json:"name"`
			ID      string `json:"id"`
			Version string `json:"version"`
			Env     string `json:"environment"`
			Commit  string `json:"commit"`
		}{
			Name:    ComponentName,
			ID:      ComponentID,
			Version: version,
			Env:     environment,
			Commit:  gitCommit,
		}

		var j, err = json.MarshalIndent(info, "", "  ")
		if err != nil {
			w.WriteHeader(http.StatusInternalServerError)
		} else {
			w.WriteHeader(http.StatusOK)
			w.Write(j)
		}
	}
}

func config(logger log.Logger) *viper.Viper {
	logger.Log("msg", "load configuration and command args")

	var v = viper.New()

	// Component default.
	v.SetDefault("config-file", "./configs/keycloak_bridge.yml")
	v.SetDefault("component-http-host-port", "0.0.0.0:8888")
	v.SetDefault("component-grpc-host-port", "0.0.0.0:5555")

	// Flaki default.
	v.SetDefault("flaki-host-port", "")

	// Keycloak default.
	v.SetDefault("keycloak-host-port", "127.0.0.1:8080")
	v.SetDefault("keycloak-username", "")
	v.SetDefault("keycloak-password", "")
	v.SetDefault("keycloak-timeout", "5s")

	// Elasticsearch default.
	v.SetDefault("es-host-port", "elasticsearch:9200")
	v.SetDefault("es-index-name", "keycloak_business")

	// Influx DB client default.
	v.SetDefault("influx", false)
	v.SetDefault("influx-host-port", "")
	v.SetDefault("influx-username", "")
	v.SetDefault("influx-password", "")
	v.SetDefault("influx-database", "")
	v.SetDefault("influx-precision", "")
	v.SetDefault("influx-retention-policy", "")
	v.SetDefault("influx-write-consistency", "")
	v.SetDefault("influx-write-interval", "1s")

	// Sentry client default.
	v.SetDefault("sentry", false)
	v.SetDefault("sentry-dsn", "")

	// Jaeger tracing default.
	v.SetDefault("jaeger", false)
	v.SetDefault("jaeger-sampler-type", "")
	v.SetDefault("jaeger-sampler-param", 0)
	v.SetDefault("jaeger-sampler-host-port", "")
	v.SetDefault("jaeger-reporter-logspan", false)
	v.SetDefault("jaeger-write-interval", "1s")
	v.SetDefault("jaeger-collector-healthcheck-host-port", "")

	// Debug routes enabled.
	v.SetDefault("pprof-route-enabled", true)

	// Redis.
	v.SetDefault("redis", false)
	v.SetDefault("redis-host-port", "")
	v.SetDefault("redis-password", "")
	v.SetDefault("redis-database", 0)
	v.SetDefault("redis-write-interval", "1s")

	// Cockroach.
	v.SetDefault("cockroach", false)
	v.SetDefault("cockroach-host-port", "")
	v.SetDefault("cockroach-username", "")
	v.SetDefault("cockroach-password", "")
	v.SetDefault("cockroach-database", "")
	v.SetDefault("cockroach-clean-interval", "24h")

	// Jobs
	v.SetDefault("job-influx-health-validity", "1m")
	v.SetDefault("job-jaeger-health-validity", "1m")
	v.SetDefault("job-redis-health-validity", "1m")
	v.SetDefault("job-sentry-health-validity", "1m")
	v.SetDefault("job-keycloak-health-validity", "1m")

	// Rate limiting (in requests/second)
	v.SetDefault("rate-event", 1000)
	v.SetDefault("rate-user", 1000)
	v.SetDefault("rate-influx-health-exec", 1000)
	v.SetDefault("rate-influx-health-read", 1000)
	v.SetDefault("rate-jaeger-health-exec", 1000)
	v.SetDefault("rate-jaeger-health-read", 1000)
	v.SetDefault("rate-redis-health-exec", 1000)
	v.SetDefault("rate-redis-health-read", 1000)
	v.SetDefault("rate-sentry-health-exec", 1000)
	v.SetDefault("rate-sentry-health-read", 1000)
	v.SetDefault("rate-keycloak-health-exec", 1000)
	v.SetDefault("rate-keycloak-health-read", 1000)
	v.SetDefault("rate-all-health", 1000)

	// First level of override.
	pflag.String("config-file", v.GetString("config-file"), "The configuration file path can be relative or absolute.")
	v.BindPFlag("config-file", pflag.Lookup("config-file"))
	pflag.Parse()

	// Load and log config.
	v.SetConfigFile(v.GetString("config-file"))
	var err = v.ReadInConfig()
	if err != nil {
		logger.Log("error", err)
	}

	// If the host/port is not set, we consider the components deactivated.
	v.Set("influx", v.GetString("influx-host-port") != "")
	v.Set("sentry", v.GetString("sentry-dsn") != "")
	v.Set("jaeger", v.GetString("jaeger-sampler-host-port") != "")
	v.Set("redis", v.GetString("redis-host-port") != "")
	v.Set("cockroach", v.GetString("cockroach-host-port") != "")

	// Log config in alphabetical order.
	var keys = v.AllKeys()
	sort.Strings(keys)

	for _, k := range keys {
		logger.Log(k, v.Get(k))
	}
	return v
}
