# Component configs
component-name: keycloak-bridge
component-http-host-port: 0.0.0.0:8880
component-grpc-host-port: 0.0.0.0:5550

# Flaki ID generator
flaki-host-port: 127.0.0.1:5555

# Keycloak configs
keycloak-host-port: 10.244.18.2:8080
keycloak-username: admin
keycloak-password: admin
keycloak-timeout-ms: 5000

# Redis
#redis-host-port: 172.19.0.1:6379
redis-password: redis
redis-database: 0
redis-write-interval-ms: 1000

# Influx DB configs
#influx-host-port: 172.19.0.1:8086
influx-username: flaki
influx-password: flaki
influx-database: flakimetrics
influx-precision: s
influx-retention-policy: ""
influx-write-consistency: ""
influx-write-interval-ms: 1000

# Sentry configs
#sentry-dsn: "https://9daea4ff2b3743fa8b18ed1a17d58051:c16ceab18b73411698f7ce11b469982c@sentry.io/270124"

# Jaeger configs
jaeger-sampler-type: const
jaeger-sampler-param: 1
jaeger-sampler-host-port: 127.0.0.1:5775
jaeger-reporter-logspan: false
jaeger-write-interval-ms: 1000
jaeger-collector-healthcheck-host-port: 127.0.0.1:14269

# Debug routes
pprof-route-enabled: true
