openapi: 3.0.1
info:
  title: Swagger Cloudtrust Management
  description: 'Statistics API for Cloudtrust.'
  version: 1.0.0
servers:
- url: http://localhost:8877
tags:
- name: Statistics
  description: Statistics management
paths:
  /statistics/actions:
    get:
      tags:
      - Actions
      summary: Get the list of all possible actions
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /statistics/realms/{realm}:
    get:
      tags:
      - Statistics
      summary: Get the statistics for a realm
      parameters:
      - name: realm
        in: path
        description: realm name (not id!)
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Statistics'
  /statistics/realms/{realm}/users:
    get:
      tags:
      - Statistics
      summary: Get the statistics on the users, for a certain realm
      parameters:
      - name: realm
        in: path
        description: realm name (not id!)
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatisticsUsers'   
  /statistics/realms/{realm}/authenticators:
    get:
      tags:
      - Statistics
      summary: Get the statistics on the authenticators used by the users, for a certain realm
      parameters:
      - name: realm
        in: path
        description: realm name (not id!)
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatisticsAuthenticators'  
  /statistics/realms/{realm}/authentications-graph:
    get:
      tags:
      - Statistics
      summary: Get the statistics on the authentications, on different time periods, for a certain realm
      parameters:
      - name: realm
        in: path
        description: realm name (not id!)
        required: true
        schema:
          type: string
      - name: unit
        in: query
        description: unit of time, i.e. hours, days or months
        required: true
        schema:
          type: string
      - name: timeshift
        in: query
        description: timeshift compared to UTC in minutes. Must start with + or - (default +0)
        required: false
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatisticsAuthentications'     
  /statistics/realms/{realm}/authentications-log:
    get:
      tags:
      - Statistics
      summary: Get the information on the last authentications, successful or failed, for a certain realm
      parameters:
      - name: realm
        in: path
        description: realm name (not id!)
        required: true
        schema:
          type: string
      - name: max
        in: query
        description: number of authentications 
        required: true
        schema:
          type: string          
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StatisticsConnection'                                               
components:
  schemas:
    Statistics:
      type: object
      properties:
        lastConnection:
          type: number
        totalConnections:
          type: object
          properties:
            lastTwelveHours:
              type: number
            lastDay:
              type: number
            lastWeek:
              type: number
            lastMonth:
              type: number
            lastYear:
              type: number
    StatisticsUsers:
      type: object
      properties:
        total:
          type: number
        disabled:
          type: number
        inactive:
          type: number      
    StatisticsAuthenticators:
      type: object
      additionalProperties:
        type: number       
    StatisticsAuthentications:
      type: array
      items:
        type: array
        items:
          type: integer  
        minItems: 2
        maxItems: 2        
    StatisticsConnection:
      type: object
      properties:
        date:
          type: string 
        result:
          type: string
        user:
          type: string
        IP: 
          type: string    
  securitySchemes:
    openId:
      type: openIdConnect
      openIdConnectUrl: http://toto.com/.well-known/openid-configuration
security:
  - openId:
    - todo