// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/cloudtrust/keycloak-bridge/pkg/components (interfaces: KeycloakComponentClient,Component)
//
// Generated by this command:
//
//	mockgen --build_flags=--mod=mod -destination=./mock/keycloak_component_client.go -package=mock -mock_names=KeycloakComponentClient=KeycloakComponentClient,Component=Component github.com/cloudtrust/keycloak-bridge/pkg/components KeycloakComponentClient,Component
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	apiidp "github.com/cloudtrust/keycloak-bridge/api/components"
	keycloak "github.com/cloudtrust/keycloak-client/v2"
	gomock "go.uber.org/mock/gomock"
)

// KeycloakComponentClient is a mock of KeycloakComponentClient interface.
type KeycloakComponentClient struct {
	ctrl     *gomock.Controller
	recorder *KeycloakComponentClientMockRecorder
	isgomock struct{}
}

// KeycloakComponentClientMockRecorder is the mock recorder for KeycloakComponentClient.
type KeycloakComponentClientMockRecorder struct {
	mock *KeycloakComponentClient
}

// NewKeycloakComponentClient creates a new mock instance.
func NewKeycloakComponentClient(ctrl *gomock.Controller) *KeycloakComponentClient {
	mock := &KeycloakComponentClient{ctrl: ctrl}
	mock.recorder = &KeycloakComponentClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *KeycloakComponentClient) EXPECT() *KeycloakComponentClientMockRecorder {
	return m.recorder
}

// CreateComponent mocks base method.
func (m *KeycloakComponentClient) CreateComponent(accessToken, realmName string, comp keycloak.ComponentRepresentation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateComponent", accessToken, realmName, comp)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateComponent indicates an expected call of CreateComponent.
func (mr *KeycloakComponentClientMockRecorder) CreateComponent(accessToken, realmName, comp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateComponent", reflect.TypeOf((*KeycloakComponentClient)(nil).CreateComponent), accessToken, realmName, comp)
}

// GetComponents mocks base method.
func (m *KeycloakComponentClient) GetComponents(accessToken, realmName string, paramKV ...string) ([]keycloak.ComponentRepresentation, error) {
	m.ctrl.T.Helper()
	varargs := []any{accessToken, realmName}
	for _, a := range paramKV {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetComponents", varargs...)
	ret0, _ := ret[0].([]keycloak.ComponentRepresentation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComponents indicates an expected call of GetComponents.
func (mr *KeycloakComponentClientMockRecorder) GetComponents(accessToken, realmName any, paramKV ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{accessToken, realmName}, paramKV...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComponents", reflect.TypeOf((*KeycloakComponentClient)(nil).GetComponents), varargs...)
}

// UpdateComponent mocks base method.
func (m *KeycloakComponentClient) UpdateComponent(accessToken, realmName, compID string, comp keycloak.ComponentRepresentation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateComponent", accessToken, realmName, compID, comp)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateComponent indicates an expected call of UpdateComponent.
func (mr *KeycloakComponentClientMockRecorder) UpdateComponent(accessToken, realmName, compID, comp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateComponent", reflect.TypeOf((*KeycloakComponentClient)(nil).UpdateComponent), accessToken, realmName, compID, comp)
}

// Component is a mock of Component interface.
type Component struct {
	ctrl     *gomock.Controller
	recorder *ComponentMockRecorder
	isgomock struct{}
}

// ComponentMockRecorder is the mock recorder for Component.
type ComponentMockRecorder struct {
	mock *Component
}

// NewComponent creates a new mock instance.
func NewComponent(ctrl *gomock.Controller) *Component {
	mock := &Component{ctrl: ctrl}
	mock.recorder = &ComponentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Component) EXPECT() *ComponentMockRecorder {
	return m.recorder
}

// CreateComponent mocks base method.
func (m *Component) CreateComponent(ctx context.Context, realmName string, comp apiidp.ComponentRepresentation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateComponent", ctx, realmName, comp)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateComponent indicates an expected call of CreateComponent.
func (mr *ComponentMockRecorder) CreateComponent(ctx, realmName, comp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateComponent", reflect.TypeOf((*Component)(nil).CreateComponent), ctx, realmName, comp)
}

// GetComponents mocks base method.
func (m *Component) GetComponents(ctx context.Context, realmName string, providerType *string) ([]apiidp.ComponentRepresentation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetComponents", ctx, realmName, providerType)
	ret0, _ := ret[0].([]apiidp.ComponentRepresentation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetComponents indicates an expected call of GetComponents.
func (mr *ComponentMockRecorder) GetComponents(ctx, realmName, providerType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetComponents", reflect.TypeOf((*Component)(nil).GetComponents), ctx, realmName, providerType)
}

// UpdateComponent mocks base method.
func (m *Component) UpdateComponent(ctx context.Context, realmName, compID string, comp apiidp.ComponentRepresentation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateComponent", ctx, realmName, compID, comp)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateComponent indicates an expected call of UpdateComponent.
func (mr *ComponentMockRecorder) UpdateComponent(ctx, realmName, compID, comp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateComponent", reflect.TypeOf((*Component)(nil).UpdateComponent), ctx, realmName, compID, comp)
}
