//Generated by gRPC Go plugin
//If you make any local changes, they will be lost
//source: users

package fb

import "github.com/google/flatbuffers/go"

import (
  context "golang.org/x/net/context"
  grpc "google.golang.org/grpc"
)

// Client API for UserService service
type UserServiceClient interface{
  GetUsers(ctx context.Context, in *flatbuffers.Builder, 
  	opts... grpc.CallOption) (* GetUsersResponse, error)  
}

type userServiceClient struct {
  cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
  return &userServiceClient{cc}
}

func (c *userServiceClient) GetUsers(ctx context.Context, in *flatbuffers.Builder, 
	opts... grpc.CallOption) (* GetUsersResponse, error) {
  out := new(GetUsersResponse)
  err := grpc.Invoke(ctx, "/fb.UserService/GetUsers", in, out, c.cc, opts...)
  if err != nil { return nil, err }
  return out, nil
}

// Server API for UserService service
type UserServiceServer interface {
  GetUsers(context.Context, *GetUsersRequest) (*flatbuffers.Builder, error)  
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
  s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_GetUsers_Handler(srv interface{}, ctx context.Context,
	dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
  in := new(GetUsersRequest)
  if err := dec(in); err != nil { return nil, err }
  if interceptor == nil { return srv.(UserServiceServer).GetUsers(ctx, in) }
  info := &grpc.UnaryServerInfo{
    Server: srv,
    FullMethod: "/fb.UserService/GetUsers",
  }
  
  handler := func(ctx context.Context, req interface{}) (interface{}, error) {
    return srv.(UserServiceServer).GetUsers(ctx, req.(* GetUsersRequest))
  }
  return interceptor(ctx, in, info, handler)
}


var _UserService_serviceDesc = grpc.ServiceDesc{
  ServiceName: "fb.UserService",
  HandlerType: (*UserServiceServer)(nil),
  Methods: []grpc.MethodDesc{
    {
      MethodName: "GetUsers",
      Handler: _UserService_GetUsers_Handler, 
    },
  },
  Streams: []grpc.StreamDesc{
  },
}

